### PR TITLE
Unleashing the Design 

### PR DESCRIPTION
**Pull request by Aquentus**
I have redesigned the website to make it more visibly appealing as well as organised the content in a modern fashion. There are still some changes that need to be made in line with suggestions raised in the Bitco.in/forum, but the pull should be fine to be merged as is with any further changes being cosmetic.

### CODE REVIEW

**Comment by thofmann** [comment]
This looks like a huge improvement to me. Out of curiosity, are you using a template from somewhere or did you you create this yourself?

I've forked your project to make a few small changes and rebase to gandrewstone's master. I will make a new pull request soon.

**Comment by thofmann** [comment]
For reference, here's the home page before and after this PR:

before

after

**Comment by Aquentus** [comment]
Thanks. It was adapted from a template so you will find a lot of unnecessary code there as I didn't have time to tidy up everything. 

I've been taking feedback here: https://bitco.in/forum/threads/bitcoin-unlimited-visual-identity.206/  and there are still things to tidy up and do, but I guess that never ends haha. I think anything is better than the current version, other changes can be made progressively. 

@theZerg was considering of adding Meteor for backend though so I guess perhaps that's what's holding up the merging. He is prob extremely busy as well with the main BU code development. Guess should ask for commit rights for the site after announcing that I am running for secretary as with him now being quite busy it would prob take forever for changes to be made otherwise.

**Comment by thofmann** [comment]
No problem.

>I've been taking feedback here: https://bitco.in/forum/threads/bitcoin-unlimited-visual-identity.206/ and there are still things to tidy up and do, but I guess that never ends haha.

Great, I'll take a look!

>@theZerg was considering of adding Meteor for backend

I haven't used Meteor before, usually going with Node.js/express as a server and various front end languages (Jade, Stylus, etc.) and frameworks (React.js, Bootstrap, Pure.css, etc.). There are a few benefits for a Node.js application, such as easy functional and unit tests with tools like Grunt and Mocha. You can also use bower to handle framework dependencies such as Bootstrap or jQuery. I'm open to working with anything, though, so Meteor is fine by me if that's what works for everyone else.

**Comment by Aquentus** [comment]
Cool, good to know someone else is willing to help. We'll probably need to add a member's section with sign up, member's unique page and all that. I haven't yet started working on it as we still considering on how to prevent sybil voting https://bitco.in/forum/threads/bitcoin-unlimited-ideas-arguments-and-proposals.123/page-6#post-7728 but we can probably whitelist current forum members for now as suggested https://bitco.in/forum/threads/gold-collapsing-bitcoin-up.16/page-213#post-7746

**Comment by gandrewstone** [comment]
Are the files in this pull request the actual source or are they the output of some entity that somehow merges content with a template?  It seems like every file is touched whether any changes were made or not, and that stuff like the header and footer are included in every file.  It is going to be very difficult to maintain this -- for example, how do you add a menu item to the footer?  You have to add it to every page.

We want to check in the ultimate source files (content and template), then we can run whatever script we need to to combine them on web host, or have the web framework combine them automatically.

**Comment by Aquentus** [comment]
They are all actual source. The code needs a lot of tidying up, like as you mentioned moving headers/footers to a template, removing unnecessary code etc, but I wanted to get something visually appealing up and running first as soon as possible so that new visitors are not put off by the design, and then the code can be tidied up, other features added, etc. 

Otherwise it is going to take some time to make everything neat while the site remains not updated

**Comment by thofmann** [comment]
I would be happy to do some tidying up, but I'm waiting to see if this is merged so I know I'm not working on a branch that will be "orphaned" :wink:

**Comment by BloomieBTC** [comment]
Could use a 'Forum' link in the top menu  :)

**Comment by Aquentus** [comment]
Yup, I certainly thought of that BloomieBTC, but we want the first version to go live so that current visitors are not put off by the design and so that we know it won't be "orphaned".

**Comment by gandrewstone** [comment]
thofmann don't worry there's no chance that this is going to be orphaned.  But at this point hold off on tidying up I should have it merged in a few hrs...

**Pull request merged**
